"""Public Python API for the Apostate native Chromium distribution."""

from .binary import (
    BinaryManager,
    DiscoveredBinary,
    binary_info,
    clear_cache,
    discover_binary,
    discovery_report,
    ensure_binary,
    target_platform,
)
from .config import (
    CATALOGUE_VERSION,
    CHROMIUM_VERSION,
    DEFAULT_PERSONA_BY_HOST,
    PACKAGE_VERSION,
    PROFILE_SCHEMA_VERSION,
    LaunchConfig,
    default_persona_for_host,
    host_persona,
    normalize_platform,
    resolve_profile as resolve_config_profile,
    translate_options,
)
from .errors import (
    ApostateError,
    BinaryError,
    BinaryNotFoundError,
    ConfigurationError,
    GeoIPError,
    GeoIPUnavailableError,
    IntegrityError,
    LaunchError,
    ManifestError,
    ProfileError,
    UnpublishedArtifactError,
    UnsupportedArchiveError,
)
from .geoip import GeoIPProvider, GeoIPResult, normalize_result, redact_proxy, resolve_geoip
from .launch import (
    DRIVERS,
    DriverSelection,
    LaunchPlan,
    driver_info,
    launch,
    launch_async,
    launch_context,
    launch_context_async,
    launch_persistent_context,
    launch_persistent_context_async,
)
from .profile_validation import load_schema, validate_profile
from .resolver import DeterministicResolver, ProfileResolution, load_catalogue, resolve, resolve_profile
from .widevine import WidevineError, discover_widevine, ensure_widevine, provision_widevine

__all__ = [
    "ApostateError",
    "BinaryError",
    "BinaryManager",
    "BinaryNotFoundError",
    "CATALOGUE_VERSION",
    "CHROMIUM_VERSION",
    "ConfigurationError",
    "DEFAULT_PERSONA_BY_HOST",
    "DeterministicResolver",
    "DiscoveredBinary",
    "GeoIPError",
    "GeoIPProvider",
    "GeoIPResult",
    "IntegrityError",
    "LaunchConfig",
    "LaunchError",
    "DRIVERS",
    "DriverSelection",
    "LaunchPlan",
    "driver_info",
    "ManifestError",
    "PACKAGE_VERSION",
    "PROFILE_SCHEMA_VERSION",
    "ProfileError",
    "ProfileResolution",
    "UnpublishedArtifactError",
    "UnsupportedArchiveError",
    "binary_info",
    "clear_cache",
    "default_persona_for_host",
    "discover_binary",
    "discovery_report",
    "ensure_binary",
    "host_persona",
    "launch",
    "launch_async",
    "launch_context",
    "launch_context_async",
    "launch_persistent_context",
    "launch_persistent_context_async",
    "load_catalogue",
    "load_schema",
    "normalize_platform",
    "normalize_result",
    "redact_proxy",
    "resolve",
    "resolve_geoip",
    "resolve_profile",
    "target_platform",
    "translate_options",
    "validate_profile",
    "WidevineError",
    "discover_widevine",
    "ensure_widevine",
    "provision_widevine",
]
