"""Canonical launch configuration and deterministic profile selection.

This module is intentionally dependency-free. It is the Python wrapper's
single translation point from user-facing snake_case options to the logical
launch contract shared by the other Apostate frontends.
"""

from __future__ import annotations

import hashlib
import importlib.resources
import json
import platform as host_platform
import re
from dataclasses import dataclass, field
from pathlib import Path
from types import MappingProxyType
from typing import Any, Callable, Mapping

from .errors import ConfigurationError, ProfileError

#: The launcher's own version, which moves independently of the binary
#: release it installs: a launcher fix does not require rebuilding Chromium,
#: and 0.1.1 installs the artifacts published as v0.1.0. What binds a package
#: to a binary release is the ``tag`` in its release manifest, not this.
PACKAGE_VERSION = "0.4.1"
CHROMIUM_VERSION = "152.0.7977.83"
CATALOGUE_VERSION = 2
PROFILE_SCHEMA_VERSION = 3
SUPPORTED_PLATFORMS = frozenset({"windows", "macos", "linux"})

#: How long a launch may spend learning where its exit is, across every
#: endpoint and retry the lookup makes. It is the one number three modules
#: need -- ``launch``'s ``geoip_timeout``, ``geoip.resolve_geoip``'s
#: ``timeout`` and ``_prelaunch_geoip``'s cascade budget -- so it lives here
#: rather than being spelled out three times. The rest of the retry policy
#: (endpoint list, attempts, backoff, per-attempt ceiling) has one consumer
#: and lives with it in ``_prelaunch_geoip``. ``npm/src/index.ts`` carries the
#: same value as ``GEOIP_BUDGET_MS``.
GEOIP_BUDGET_SECONDS = 20.0

#: Tokens the binary treats as "inherit the host and compose nothing". All six
#: are exactly equivalent and case-insensitive; ``off`` is what users arriving
#: from other anti-detect wrappers type, ``host`` is this repository's spelling.
HOST_INHERITANCE_SEEDS = frozenset({"host", "off", "false", "0", "disable", "disabled"})

#: The country -> locale policy both launchers infer a locale from, as package
#: data rather than a table in this file. It is generated by
#: ``scripts/generate-country-locales.py`` from CLDR territoryInfo and
#: Chromium's own ``kAcceptLanguageList``, and ``scripts/sync-packages.py``
#: copies it byte-identically into both packages, so one exit country resolves
#: to one locale in Python, in Node and in the browser.
#:
#: It replaced a hand-kept table of 45 countries. A Malaysian exit matched
#: nothing in that table, so the launcher announced that it had resolved no
#: locale -- declining, on a lookup that succeeded and returned MY, to do the
#: one inference it exists to do. The generated table names 257 territories,
#: which is all of them.
_COUNTRY_LOCALES_ASSET = "country-locales.json"
_COUNTRY_LOCALES: Mapping[str, str] | None = None


def _read_country_locales() -> dict[str, str]:
    """The checkout's copy when there is one, else this package's own."""
    source = Path(__file__).resolve().parents[2] / "config" / _COUNTRY_LOCALES_ASSET
    raw: str | None = None
    if source.is_file():
        try:
            raw = source.read_text(encoding="utf-8")
        except OSError:
            raw = None
    if raw is None:
        try:
            raw = (importlib.resources.files("apostate")
                   .joinpath("assets", _COUNTRY_LOCALES_ASSET).read_text(encoding="utf-8"))
        except (ModuleNotFoundError, OSError, TypeError, UnicodeDecodeError) as exc:
            raise ConfigurationError(
                "the country-locale policy asset is unavailable") from exc
    try:
        locales = json.loads(raw)["locales"]
    except (json.JSONDecodeError, KeyError, TypeError) as exc:
        raise ConfigurationError("the country-locale policy asset is malformed") from exc
    if not isinstance(locales, Mapping) or not locales:
        raise ConfigurationError("the country-locale policy asset is malformed")
    return {str(code).upper(): value for code, value in locales.items()
            if isinstance(value, str) and value}


def country_locales() -> Mapping[str, str]:
    """The whole policy table, read once."""
    global _COUNTRY_LOCALES
    if _COUNTRY_LOCALES is None:
        _COUNTRY_LOCALES = MappingProxyType(_read_country_locales())
    return _COUNTRY_LOCALES


def country_locale(code: Any) -> str | None:
    """The locale an exit in *code* implies, or ``None`` for a non-country.

    ``None`` now means "that was not a country code", not "that country is not
    in the table": every ISO-3166 territory is.
    """
    if not isinstance(code, str):
        return None
    normalized = code.strip().upper()
    if not re.fullmatch(r"[A-Z]{2}", normalized):
        return None
    return country_locales().get(normalized)


#: Every ``--fingerprint*`` switch the binary reads, as defined in
#: ``patches/``. A misspelled switch is silently ignored by Chromium, which
#: would present the operator's real machine while they believed a persona
#: was applied, so an unknown one is refused here instead of at the far end
#: of a launch.
FINGERPRINT_SWITCHES = frozenset({
    "--apostate-profile",
    "--fingerprint",
    "--fingerprint-anchor",
    "--fingerprint-device-memory",
    "--fingerprint-explain",
    "--fingerprint-gpu-renderer",
    "--fingerprint-gpu-vendor",
    "--fingerprint-hardware-concurrency",
    "--fingerprint-locale",
    "--fingerprint-noise",
    "--fingerprint-platform",
    "--fingerprint-screen-height",
    "--fingerprint-screen-width",
    "--fingerprint-timezone",
    "--fingerprint-webrtc-ip",
    "--fingerprint-webrtc-udp",
})

#: A switch this far from a known one, and not itself known, is a typo of it.
#: ``--fingeprint-platform=windows`` is one edit from ``--fingerprint-platform``
#: and Chromium drops it without a word, which turns a cross-OS launch into
#: the host's own persona while the script says otherwise.
_NEAR_MISS_DISTANCE = 2

#: Values that read as "off" on a presence-gated switch. The binary tests
#: whether ``--fingerprint-noise`` is present, never what it is set to, so
#: ``--fingerprint-noise=false`` enables noise. A competitor's documentation
#: recommends exactly that string, so operators arrive carrying it.
_OFF_TOKENS = frozenset({"false", "0", "no", "off", "disable", "disabled"})

#: Longest ``--fingerprint`` value the binary accepts before exiting non-zero.
MAX_SEED_LENGTH = 512


def _json_value(value: Any) -> Any:
    try:
        json.dumps(value, sort_keys=True, separators=(",", ":"))
    except (TypeError, ValueError) as exc:
        raise ConfigurationError(f"launch option is not JSON-compatible: {exc}") from exc
    return value


def _string_or_none(name: str, value: Any) -> str | None:
    if value is None:
        return None
    if not isinstance(value, str) or not value.strip():
        raise ConfigurationError(f"{name} must be a non-empty string or None")
    return value


def normalize_platform(value: str | None) -> str | None:
    if value is None:
        return None
    if not isinstance(value, str):
        raise ConfigurationError("fingerprint_platform must be a string or None")
    aliases = {
        "win": "windows", "win32": "windows", "darwin": "macos",
        "mac": "macos", "osx": "macos", "linux2": "linux",
    }
    normalized = aliases.get(value.strip().lower(), value.strip().lower())
    if normalized not in SUPPORTED_PLATFORMS:
        raise ConfigurationError(
            "fingerprint_platform must be one of windows, macos, or linux"
        )
    return normalized


def host_persona() -> str:
    """The fingerprint-platform token for the **host** OS.

    This is the host's own platform and never the platform a launch claims.
    The browser's default claimed persona is host-conditional and the two
    differ on a Linux host, so a caller that wants to know what a default
    launch will present must pass this through
    :func:`default_persona_for_host` rather than use it directly. Mirrors
    ``HostPlatformToken()`` in ``base/apostate/host_capability.cc``.
    """
    system = host_platform.system().lower()
    if system == "windows":
        return "windows"
    if system == "darwin":
        return "macos"
    if system == "linux":
        return "linux"
    raise ConfigurationError(f"unsupported host platform: {system or 'unknown'}")


#: The browser's default claimed persona for each host platform token, mirroring
#: ``DefaultPersonaForHost()`` in ``base/apostate/compose.cc`` (patch 0102).
#:
#: This is a deliberate second implementation of a C++ default, and it is scoped
#: to the one path that cannot avoid one. The launch path does not use it: it
#: sends no ``--fingerprint-platform`` when the user named no platform, so the
#: browser applies its own default and the table has a single owner.
#: :class:`~apostate.resolver.DeterministicResolver` composes and reports a
#: resolution locally, with no browser process to ask, so it has to know the
#: same table.
#:
#: The mapping exists nowhere but the C++; the dispersion tables under
#: ``resources/profiles/`` key option sets on a platform and so pin the token
#: set, but not the host-to-persona edge. That makes this a known coupling:
#: ``python/tests/test_package.py`` and ``npm/test/index.test.mjs`` transcribe
#: the table independently and fail if either side moves alone.
#:
#: Read-only, matching ``Object.freeze`` on the Node side: it is a transcription
#: of a C++ contract, not a setting.
DEFAULT_PERSONA_BY_HOST = MappingProxyType({
    "macos": "macos",
    "windows": "windows",
    # The one default that is not the host's own OS. A Linux host is the
    # deployment target and a Windows persona is what most launches there
    # want; the cost is the Windows font set, which the browser reports as a
    # limitation rather than hiding.
    "linux": "windows",
})


def default_persona_for_host(host_token: str) -> str:
    """The platform a default launch claims when the host reports *host_token*.

    An unrecognised or empty token is returned unchanged rather than defaulted
    to ``windows``. That is what the C++ does: the caller then fails its own
    ``IsKnownPlatform()`` check, composes nothing and inherits the host.
    Mapping an unknown host onto a persona here would instead compose profiles
    for platforms with no corpus behind them.
    """
    return DEFAULT_PERSONA_BY_HOST.get(host_token, host_token)


def is_host_seed(value: int | str | None) -> bool:
    """Whether *value* asks the binary to inherit the host instead of composing."""
    if value is None:
        return False
    return str(value).strip().lower() in HOST_INHERITANCE_SEEDS


def _normalize_seed(value: int | str | None) -> int | str | None:
    if value is None:
        return None
    if isinstance(value, int) and not isinstance(value, bool):
        if value < 0:
            raise ConfigurationError("fingerprint must be nonnegative")
        return value
    if not isinstance(value, str) or not value.strip():
        raise ConfigurationError("fingerprint must be an integer, stable string, or None")
    seed = value.strip()
    if len(seed.encode("utf-8")) > MAX_SEED_LENGTH:
        raise ConfigurationError(
            f"fingerprint must be at most {MAX_SEED_LENGTH} bytes; the binary rejects a longer seed"
        )
    if not re.fullmatch(r"[A-Za-z0-9][A-Za-z0-9._:-]*", seed):
        raise ConfigurationError("fingerprint string must match [A-Za-z0-9][A-Za-z0-9._:-]*")
    return seed


def _edit_distance(a: str, b: str, limit: int) -> int:
    """Levenshtein distance, capped at ``limit + 1`` so a far pair exits early."""
    if abs(len(a) - len(b)) > limit:
        return limit + 1
    previous = list(range(len(b) + 1))
    for i, ca in enumerate(a, 1):
        current = [i]
        for j, cb in enumerate(b, 1):
            current.append(min(previous[j] + 1, current[j - 1] + 1, previous[j - 1] + (ca != cb)))
        if min(current) > limit:
            return limit + 1
        previous = current
    return previous[-1]


def check_fingerprint_switches(args: Any) -> None:
    """Refuse an unknown ``--fingerprint*`` switch, or a typo of a known one.

    Called at config time and again when arguments are built, so a caller
    who bypasses ``translate_options`` is still covered; the check is pure.
    """
    for item in args:
        if not isinstance(item, str) or not item.startswith("--"):
            continue
        name, _, value = item.partition("=")
        if name == "--fingerprint-noise" and value.strip().lower() in _OFF_TOKENS:
            raise ConfigurationError(
                f"{item} turns readback noise ON. The switch is presence-gated: the binary "
                "tests whether it is there, not what it is set to, so any value enables it. "
                "Noise is off by default; omit the switch to keep it off."
            )
        if name in FINGERPRINT_SWITCHES:
            continue
        if name.startswith("--fingerprint"):
            raise ConfigurationError(
                f"{name} is not a switch this browser reads; Chromium would ignore it and "
                "leave that surface host-inherited. Supported: "
                + ", ".join(sorted(FINGERPRINT_SWITCHES))
            )
        for known in FINGERPRINT_SWITCHES:
            if _edit_distance(name, known, _NEAR_MISS_DISTANCE) <= _NEAR_MISS_DISTANCE:
                raise ConfigurationError(
                    f"{name} is not a switch this browser reads and looks like a typo of {known}; "
                    "Chromium would ignore it and leave that surface host-inherited"
                )


def _normalize_args(value: Any) -> list[str]:
    if value is None:
        return []
    if isinstance(value, (str, bytes)) or not isinstance(value, (list, tuple)):
        raise ConfigurationError("args must be a sequence of strings")
    args = []
    for item in value:
        if not isinstance(item, str):
            raise ConfigurationError("args must be a sequence of strings")
        args.append(item)
    check_fingerprint_switches(args)
    return args


def _path_value(value: str | Path | None, name: str) -> str | None:
    if value is None:
        return None
    if isinstance(value, Path):
        return str(value.expanduser())
    if isinstance(value, str) and value:
        return value
    raise ConfigurationError(f"{name} must be a path-like string or None")


@dataclass(frozen=True)
class LaunchConfig:
    """Immutable canonical launch configuration."""

    fingerprint: int | str | None = None
    fingerprint_platform: str | None = None
    profile: Any = None
    locale: str | None = None
    timezone: str | None = None
    geoip: bool = True
    proxy: str | Mapping[str, Any] | None = None
    headless: bool = True
    user_data_dir: str | None = None
    args: tuple[str, ...] = field(default_factory=tuple)

    def __post_init__(self) -> None:
        object.__setattr__(self, "fingerprint", _normalize_seed(self.fingerprint))
        object.__setattr__(self, "fingerprint_platform", normalize_platform(self.fingerprint_platform))
        object.__setattr__(self, "locale", _string_or_none("locale", self.locale))
        object.__setattr__(self, "timezone", _string_or_none("timezone", self.timezone))
        if not isinstance(self.geoip, bool):
            raise ConfigurationError("geoip must be a boolean")
        if not isinstance(self.headless, bool):
            raise ConfigurationError("headless must be a boolean")
        if self.proxy is not None and not isinstance(self.proxy, (str, Mapping)):
            raise ConfigurationError("proxy must be a URL, mapping, or None")
        object.__setattr__(self, "user_data_dir", _path_value(self.user_data_dir, "user_data_dir"))
        object.__setattr__(self, "args", tuple(_normalize_args(self.args)))
        if self.profile is not None and not isinstance(self.profile, (str, Path, Mapping)):
            _json_value(self.profile)

    def to_dict(self) -> dict[str, Any]:
        return {
            "fingerprint": self.fingerprint,
            "fingerprint_platform": self.fingerprint_platform,
            "profile": self.profile,
            "locale": self.locale,
            "timezone": self.timezone,
            "geoip": self.geoip,
            "proxy": self.proxy,
            "headless": self.headless,
            "user_data_dir": self.user_data_dir,
            "args": list(self.args),
        }

    def canonical_json(self) -> str:
        return json.dumps(self.to_dict(), sort_keys=True, separators=(",", ":"), default=str)

    def resolver_identity(self, *, browser_version: str = CHROMIUM_VERSION,
                          catalogue_version: int = CATALOGUE_VERSION) -> str:
        """A cache key for this launch request's resolution.

        Keyed on the request as given plus the host, never on a guess at what
        the browser will claim. This used to substitute :func:`host_persona`
        for an unspecified platform, which collapsed "no platform named" and
        an explicit persona equal to the host into one key. Since 0102 those
        are two different browsers on a Linux host -- unspecified claims
        ``windows``, explicit ``linux`` claims ``linux`` -- so that collision
        would hand one launch's cached resolution to the other. The host stays
        in the payload as its own field because the same request composes
        differently per host; keeping it separate leaves the host-to-persona
        table with a single owner in :func:`default_persona_for_host` instead
        of a copy here.
        """
        payload = {
            "fingerprint": self.fingerprint,
            "fingerprint_platform": self.fingerprint_platform,
            "host_platform": host_persona(),
            "profile": self.profile,
            "catalogue_version": catalogue_version,
            "browser_version": browser_version,
            "profile_schema_version": PROFILE_SCHEMA_VERSION,
        }
        encoded = json.dumps(payload, sort_keys=True, separators=(",", ":"), default=str).encode()
        return hashlib.sha256(encoded).hexdigest()


Resolver = Callable[[LaunchConfig], Mapping[str, Any]]


def translate_options(
    *,
    fingerprint: int | str | None = None,
    fingerprint_platform: str | None = None,
    profile: Any = None,
    locale: str | None = None,
    timezone: str | None = None,
    geoip: bool = True,
    proxy: str | Mapping[str, Any] | None = None,
    headless: bool = True,
    user_data_dir: str | Path | None = None,
    args: list[str] | tuple[str, ...] | None = None,
    **unknown: Any,
) -> LaunchConfig:
    """Translate public Python keyword options into canonical snake_case."""
    if unknown:
        names = ", ".join(sorted(unknown))
        raise ConfigurationError(f"unsupported launch option(s): {names}")
    return LaunchConfig(
        fingerprint=fingerprint,
        fingerprint_platform=fingerprint_platform,
        profile=profile,
        locale=locale,
        timezone=timezone,
        geoip=geoip,
        proxy=proxy,
        headless=headless,
        user_data_dir=user_data_dir,
        args=tuple(_normalize_args(args)),
    )


def resolve_profile(config: LaunchConfig, resolver: Resolver | None = None) -> dict[str, Any] | None:
    """Resolve an explicit profile through an injectable resolver boundary."""
    if config.profile is None and resolver is None:
        return None
    if config.profile is not None:
        profile = config.profile
        if isinstance(profile, (str, Path)):
            path = Path(profile).expanduser()
            try:
                profile = json.loads(path.read_text(encoding="utf-8"))
            except OSError as exc:
                raise ProfileError(f"unable to read profile file {path}: {exc}") from exc
            except json.JSONDecodeError as exc:
                raise ProfileError(f"profile file is not valid JSON: {path}") from exc
        if not isinstance(profile, Mapping):
            raise ProfileError("profile must be a mapping or JSON profile path")
        return dict(profile)
    assert resolver is not None
    resolved = resolver(config)
    if not isinstance(resolved, Mapping):
        raise ProfileError("profile resolver must return a mapping")
    return dict(resolved)


__all__ = [
    "PACKAGE_VERSION", "CHROMIUM_VERSION", "CATALOGUE_VERSION",
    "PROFILE_SCHEMA_VERSION", "GEOIP_BUDGET_SECONDS", "DEFAULT_PERSONA_BY_HOST",
    "LaunchConfig",
    "Resolver", "default_persona_for_host", "host_persona",
    "normalize_platform", "resolve_profile", "translate_options",
]
